import os
import json
import time
import google.generativeai as genai
import google.api_core.exceptions
from dotenv import load_dotenv

def parse_json(text: str) -> dict:
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    if text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    return json.loads(text.strip())

def generate_content_with_retry(model, prompt, retries=5, delay=6) -> any:
    for i in range(retries):
        try:
            return model.generate_content(prompt)
        except google.api_core.exceptions.ResourceExhausted as e:
            if i == retries - 1:
                raise e
            print(f"  Rate limit hit (429). Retrying in {delay} seconds...", flush=True)
            time.sleep(delay)
            delay *= 2
        except Exception as e:
            raise e

def run(inputs: dict, output_dir: str) -> dict:
    # 1. Load environment variables
    load_dotenv()
    
    # Sibling fallback
    if not os.getenv("GEMINI_API_KEY"):
        sibling_env = "D:/Javed/outskill/outskill/.env"
        if os.path.exists(sibling_env):
            load_dotenv(sibling_env)

    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY environment variable is not set.")

    genai.configure(api_key=api_key)

    goal = inputs.get("goal")
    if not goal:
        raise ValueError("Input 'goal' is required.")

    print(f"Planning subtasks for goal: '{goal}'", flush=True)

    # Use gemini-3.5-flash
    model = genai.GenerativeModel("gemini-3.5-flash")

    prompt = f"""You are a master software architect. Given the following user goal:
"{goal}"

Break it down into a concise, ordered list of executable subtasks. Each subtask must be detailed enough that a code generator agent can implement it in one go.
Examples of subtasks:
- "Create a requirements.txt with fastapi and uvicorn dependencies"
- "Create app/main.py with basic FastAPI server and items GET/POST routes"
- "Create README.md with run instructions"

You MUST respond ONLY with a JSON object in this format:
{{
  "subtasks": [
    "subtask 1",
    "subtask 2",
    ...
  ]
}}
"""

    response = generate_content_with_retry(model, prompt)
    data = parse_json(response.text)

    subtasks = data.get("subtasks", [])
    if not subtasks:
        raise ValueError("Gemini returned empty subtasks plan.")

    # Write plan.md in output_dir
    os.makedirs(output_dir, exist_ok=True)
    plan_path = os.path.join(output_dir, "plan.md")
    with open(plan_path, "w", encoding="utf-8") as f:
        f.write(f"# Implementation Plan for: {goal}\n\n")
        f.write("Generated by Planner Agent.\n\n")
        f.write("## Subtasks\n\n")
        for i, task in enumerate(subtasks, 1):
            f.write(f"- [ ] **Subtask {i}**: {task}\n")

    print(f"Successfully wrote plan.md with {len(subtasks)} subtasks.", flush=True)

    return {"plan": subtasks}
